export enum Region {
  br1 = 'americas',
  la1 = 'americas',
  la2 = 'americas',
  na1 = 'americas',
  oc1 = 'americas',
  jp1 = 'asia',
  kr = 'asia',
  ru = 'asia',
  sg2 = 'asia',
  th2 = 'asia',
  tw2 = 'asia',
  vn2 = 'asia',
  eun1 = 'europe',
  euw1 = 'europe',
  tr1 = 'europe',
  ph2 = 'sea',
}
